-- CASO NÃO EXISTA A TABELA WALLETS, ELA SERÁ CRIADA
-- TODAS AS COLUNAS, MESMOS NOMES QUE ESTÃO NA ENTIDADE WALLETS
CREATE TABLE IF NOT EXISTS WALLETS (
    ID SERIAL PRIMARY KEY, FULL_NAME VARCHAR(100), CPF BIGINT, EMAIL VARCHAR(100),
    "PASSWORD" VARCHAR(100), "TYPE" INT, BALANCE DECIMAL(10,2)
);


-- REGRA UNIQUE PARA LIMITAR DIRETAMENTO NO BANCO DE DADOS
-- NESSE CASO VAI GARANTIR QUE NUNCA SERÁ CRIADO UMA WALLET PRO MESMO CPF E EMAIL CASO ELES JÁ ESTEJAM LIGADOS A UMA WALLET
CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON WALLETS (CPF);
CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON WALLETS (EMAIL);

-- CASO NÃO EXISTA A TABELA TRANSACTIONS, ELA SERÁ CRIADA
-- TODAS AS COLUNAS, MESMOS NOMES QUE ESTÃO NA ENTIDADE TRANSACTIONS
-- TEM MAPEAMENTO DAS CHAVES ESTRANGEIRAS, O PAYER E PAYEE VÃO APONTAR PARA O ID DA WALLET
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    I SERIAL PRIMARY KEY, PAYER INT, PAYEE INT, "VALUE" DECIMAL(10, 2),
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (PAYER) REFERENCES WALLETS (ID),
    FOREIGN KEY (PAYEE) REFERENCES WALLETS (ID)
);